[build]
  command = "CI= npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  
  # Environment variables
  NEXT_PUBLIC_SUPABASE_URL = "https://hhxlbwkhsogifgwlxuru.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoeGxid2toc29naWZnd2x4dXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjcwMDEsImV4cCI6MjA2MzkwMzAwMX0.XehmZ9I1UU-nyL73NyfXzbuOA5qc-Je8QGQEUNbDcko"
  NEXT_PUBLIC_API_URL = "https://ecotalk-server.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# For client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
